services:
  postgres-db:
    image: postgres:15-alpine

    container_name: volunteerhub_postgres

    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=volunteerhub

    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

    restart: always

  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: volunteerhub_rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=myuser
      - RABBITMQ_DEFAULT_PASS=mypassword

  redis:
    image: redis:7-alpine
    container_name: volunteerhub_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: always

  backend:
    build: ./backend
    container_name: volunteerhub_backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/volunteerhub
      - SPRING_DATASOURCE_USERNAME=myuser
      - SPRING_DATASOURCE_PASSWORD=mypassword
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_DATA_REDIS_HOST=redis
      - RATE_LIMIT_REDIS_HOST=redis
    depends_on:
      - postgres-db
      - rabbitmq
      - redis
    restart: always

volumes:
  postgres_data:
    driver: local
  rabbitmq_data:
    driver: local
  redis_data:
    driver: local
