services:
  postgres-db:
    image: postgres:15-alpine

    container_name: volunteerhub_postgres

    labels:
      logging: "promtail"

    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=volunteerhub

    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

    restart: always

  backend:
    build: ./backend
    container_name: volunteerhub_backend
    labels:
      logging: "promtail"
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/volunteerhub
      - SPRING_DATASOURCE_USERNAME=myuser
      - SPRING_DATASOURCE_PASSWORD=mypassword
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_DATA_REDIS_HOST=redis
      - SPRING_MAIL_HOST=smtp.gmail.com
      - SPRING_MAIL_PORT=587
      - SPRING_MAIL_USERNAME=user@example.com
      - SPRING_MAIL_PASSWORD=xxxx xxxx xxxx xxxx
      - SPRING_MAIL_PASSWORD=xxxx xxxx xxxx xxxx
      - PROMETHEUS_URL=http://prometheus:9090
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_JPA_SHOW_SQL=false
    depends_on:
      - postgres-db
      - rabbitmq
      - redis
    restart: always

  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: volunteerhub_rabbitmq
    labels:
      logging: "promtail"
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=myuser
      - RABBITMQ_DEFAULT_PASS=mypassword

  redis:
    image: redis:7-alpine
    container_name: volunteerhub_redis
    labels:
      logging: "promtail"
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: always

  prometheus:
    image: prom/prometheus:latest
    container_name: volunteerhub_prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    restart: always

  grafana:
    image: grafana/grafana:latest
    container_name: volunteerhub_grafana
    ports:
      - "3001:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_PUBLIC_DASHBOARDS_ENABLED=true
    volumes:
      - grafana_data:/var/lib/grafana
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning
    depends_on:
      - prometheus
      - loki
    restart: always

  loki:
    image: grafana/loki:3.0.0
    container_name: volunteerhub_loki
    ports:
      - "3100:3100"
    volumes:
      - ./monitoring/loki/loki-config.yml:/etc/loki/loki-config.yml
      - loki_data:/loki
    command: -config.file=/etc/loki/loki-config.yml
    restart: always

  tempo:
    image: grafana/tempo:latest
    container_name: volunteerhub_tempo
    user: root
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - ./monitoring/tempo/tempo-config.yml:/etc/tempo.yaml
      - tempo_data:/tmp/tempo
    ports:
      - "14268:14268" # jaeger ingest
      - "3200:3200" # tempo
      - "3202:3202"
      - "9411:9411" # zipkin
    restart: always

  promtail:
    image: grafana/promtail:3.0.0
    container_name: volunteerhub_promtail
    volumes:
      - ./monitoring/promtail/promtail-config.yml:/etc/promtail/promtail-config.yml
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
    command: -config.file=/etc/promtail/promtail-config.yml
    depends_on:
      - loki
    restart: always

volumes:
  postgres_data:
    driver: local
  rabbitmq_data:
    driver: local
  redis_data:
    driver: local
  prometheus_data:
    driver: local
  grafana_data:
    driver: local
  loki_data:
    driver: local
  tempo_data:
    driver: local
